
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDECOMMA DIVIDE ID KEYWORD LPARENTHESIS MINUS NUMBER PLUS RPARENTHESIS TIMES\n    expression : ID LPARENTHESIS args RPARENTHESIS\n               | expression PLUS term\n               | expression MINUS term\n               | term\n               | KEYWORD\n    \n    args : expression\n    \n    args : args COMMA expression\n    \n    term : term TIMES factor\n         | term DIVIDE factor\n         | factor\n    \n    factor : NUMBER\n           | LPARENTHESIS expression RPARENTHESIS\n    '
    
_lr_action_items = {'ID':([0,3,10,22,],[2,2,2,2,]),'KEYWORD':([0,3,10,22,],[5,5,5,5,]),'NUMBER':([0,3,8,9,10,12,13,22,],[7,7,7,7,7,7,7,7,]),'LPARENTHESIS':([0,2,3,8,9,10,12,13,22,],[3,10,3,3,3,3,3,3,3,]),'$end':([1,4,5,6,7,14,15,18,19,20,21,],[0,-4,-5,-10,-11,-2,-3,-12,-8,-9,-1,]),'PLUS':([1,4,5,6,7,11,14,15,17,18,19,20,21,23,],[8,-4,-5,-10,-11,8,-2,-3,8,-12,-8,-9,-1,8,]),'MINUS':([1,4,5,6,7,11,14,15,17,18,19,20,21,23,],[9,-4,-5,-10,-11,9,-2,-3,9,-12,-8,-9,-1,9,]),'RPARENTHESIS':([4,5,6,7,11,14,15,16,17,18,19,20,21,23,],[-4,-5,-10,-11,18,-2,-3,21,-6,-12,-8,-9,-1,-7,]),'COMMA':([4,5,6,7,14,15,16,17,18,19,20,21,23,],[-4,-5,-10,-11,-2,-3,22,-6,-12,-8,-9,-1,-7,]),'TIMES':([4,6,7,14,15,18,19,20,],[12,-10,-11,12,12,-12,-8,-9,]),'DIVIDE':([4,6,7,14,15,18,19,20,],[13,-10,-11,13,13,-12,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,10,22,],[1,11,17,23,]),'term':([0,3,8,9,10,22,],[4,4,14,15,4,4,]),'factor':([0,3,8,9,10,12,13,22,],[6,6,6,6,6,19,20,6,]),'args':([10,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ID LPARENTHESIS args RPARENTHESIS','expression',4,'p_expression_function_call','parser_1.py',35),
  ('expression -> expression PLUS term','expression',3,'p_expression_function_call','parser_1.py',36),
  ('expression -> expression MINUS term','expression',3,'p_expression_function_call','parser_1.py',37),
  ('expression -> term','expression',1,'p_expression_function_call','parser_1.py',38),
  ('expression -> KEYWORD','expression',1,'p_expression_function_call','parser_1.py',39),
  ('args -> expression','args',1,'p_args_single','parser_1.py',53),
  ('args -> args COMMA expression','args',3,'p_args_multiple','parser_1.py',59),
  ('term -> term TIMES factor','term',3,'p_term','parser_1.py',65),
  ('term -> term DIVIDE factor','term',3,'p_term','parser_1.py',66),
  ('term -> factor','term',1,'p_term','parser_1.py',67),
  ('factor -> NUMBER','factor',1,'p_factor','parser_1.py',79),
  ('factor -> LPARENTHESIS expression RPARENTHESIS','factor',3,'p_factor','parser_1.py',80),
]
